baseurl                 = "/"               
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "I'm a demo!"
theme                   = "sam"

[params]
    dateform            = "Mon, 02. Jan 2006"
    dateformfull        = "Mon, 02. Jan 2006 15:04:05 CEST"
    # favicon             = "sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    footerText          = "I'm a demo for a guy called Tim."

# Metadata
    description         = "I nice little demo"            # Max 160 characters show in search results

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/about"
    text = "new phone, who dis?"
